FROM google/cloud-sdk:slim
RUN apt install -y wget  &&  rm -rf /var/lib/apt/lists/*
RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
RUN echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list && \
    apt-get update && apt-get install -y mongodb-org-tools && rm -rf /var/lib/apt/lists/*

ADD ./backup.sh /mongodb-gcs-backup/backup.sh

RUN chmod +x /mongodb-gcs-backup/backup.sh

ENTRYPOINT ["/mongodb-gcs-backup/backup.sh"]


